#	module 	0-system
#	section 000-communs
#   node    boss_activite_fr.yaml
#   lang    fr
#	refNode	20_000_5
#Principe des règles
    # regle_1_1_1 (&&[par_1,par_2,...,])
    # regle_1_1_2 (&&[par_1,par_2,...,])
    # regle_1_1_1 || regle_1_1_2

type_doc:
    #seul le user peu acceder au document
    groupeDoc_2:              "Document personnel" 
    #droits => "[version, edition, modification, suppression, impression]
    groupeDoc_2:              "Commercial"  
    typeDoc_2_1:                    "Rapport"
    regle_2_1_1:                          "["AccreditUserMax" =>2,"Module" => "["Commercial", "Operation"],"groupe_user" => "[Commercial_0]", "droit" =>"[0,1,1,] ]"
    regle_2_1_2:                          "["AccreditUserMax" =>3,"groupe_user" => "[grp_comm_affaires]"]"

    typeDoc_2_2:                    "Journal de bord"
    regle_2_2_1:                          "["AccreditUserMax" =>2,"Module" => "["Commercial", "Operation"]
   
    groupeDoc_3:              "Operation"
    typeDoc_3_1:                    "Rapport"
    regle_3_1_1:                          "["AccreditUserMax" =>4,"Module" => "["Commercial", "Operation"]
    regle_3_1_2:                          "groupe_user" => "[grp_comm_affaires]"]"
    typeDoc_3_2:                    "Journal de bord"



