<?php
		return	[
					#	module 	0-system
					#	section 000-communs
					#	refNode	----

					#groupe_users
					"grp_system"    		=>"",
					"grp_dg"       			=>"100,101,",
					"grp_codir"       		=>"100,101,",
					"grp_comm"       		=>"103,101,",
					"grp_comm_affaires"    					=>"",
					"grp_comm_affaires_devis"    			=>"",
					"grp_comm_affaire_livrables"    		=>"",
					"grp_comm_affaire_services"    			=>"",
					"grp_comm_affaire_affaires_en_sommeil"  =>"",
					"grp_comm_affaire_affaires_clients"    	=>"",
					"grp_comm_contrats_clients"    			=>"",
					"grp_comm_services_contrats"    		=>"",
					"grp_comm_fournitures_contrats"    		=>"",
					"grp_comm_services"    					=>"",
					"grp_comm_services_taches"  			=>"",
					"grp_comm_affaire_facturation"  		=>"",
					"grp_comm_indicateurs_comm"  			=>"",
					"grp_ops_atelier"  						=>"",
					"grp_ops_intervention"  				=>"",
					"grp_ops_mise_a_disposition"  			=>"",
					"grp_ops_fabrication_par_lot"  			=>"",
					"grp_ops_fournitures"  					=>"",
					"grp_ops_vente_fournitures"  			=>"",
					"grp_ops_indicateurs"  					=>"",
					"grp_sg"  								=>"",
					"grp_sg_maintance"  					=>"",
					"grp_sg_maintance_livrables"  			=>"",
					"grp_sg_maintance_taches"  				=>"",
					"grp_sg_maintance_fournitures"  		=>"",
					"grp_sg_logistique"  					=>"",
					"grp_sg_logistique_livraisons"  		=>"",
					"grp_sg_logistique_transports"  		=>"",
					"grp_sg_logistique_fournitures"  		=>"",
					"grp_sg_projets_tn_livrables"  			=>"",
					"grp_sg_projets_tn_taches"  			=>"",
					"grp_sg_projets_tn_fournitures"  		=>"",
					"grp_sg_indicateurs"  					=>"",
					"grp_appro"  							=>"",
					"grp_appro_magasin_stocks"  			=>"",
					"grp_appro_magasin_livraison"  			=>"",
					"grp_appro_magasin_reception"  			=>"",
					"grp_appro_magasin_sorties_provisoires" =>"",
					"grp_appro_magasin_indicateurs"  		=>"",
					"grp_achats"  							=>"",
					"grp_achats_consultation"  				=>"",
					"grp_achats_commandes"  				=>"",
					"grp_achats_reception"  				=>"",
					"grp_personnel"  						=>"",
					"grp_administratif"  					=>"",
					"grp_finance"  							=>"",
					"grp_finance_budget"  					=>"",
					"grp_qualité"  							=>"",
					"grp_hierachique_3"  					=>"",
					"grp_hierachique_2"  					=>"",
					"grp_hierachique_1"  					=>"",
					"grp_hierachique_0"  					=>"",
					"grp_invite"  							=>""
				];