#	module 	0-system
#	section 130-menu_principal
#   lang    fr
#	refNode	0_130_0


texte_menu:
    mnu_1:        "Commercial"
    mnu_1_100_0:          "Affaires"
    mnu_1_400_0:          "Gestion clients"
    mnu_1_500_0:          "Contrats clients"
    mnu_1_600_0:          "Services Produits"
    mnu_1_700_0:          "Marketing"
    mnu_2:        "Opérations"
    mnu_2_100_0:          "Atelier"
    mnu_2_200_0:          "Intervention"
    mnu_3:        "Services généraux"
    mnu_3_100_0:          "Maintenance"
    mnu_3_200_0:          "Logistique"
    mnu_3_300_0:          "Projets Travaux Neufs"
    mnu_4:        "Appro"
    mnu_4_100_0:          "Besoins"
    mnu_4_200_0:          "Stock"
    mnu_4_300_0:          "Inventaires stock"
    mnu_4_400_0:          "Sorties provisoires"
    mnu_5:        "Achats"
    mnu_5_100_0:          "Achats processus"
    mnu_5_200_0:          "Fournisseurs"
    mnu_6:        "Personnel"
    mnu_6_100_0:          "Repertoire personnel"
    mnu_6_200_0:          "MPO"
    mnu_6_400_0:          "Pointage"
    mnu_6_500_0:          "Paye"
    mnu_6_600_0:          "Santé"
    mnu_6_700_0:          "Congés"
    mnu_7:        "Administratif"
    mnu_7_100_0:          "Pending"
    mnu_8:        "Finance"
    mnu_8_100_0:          "Budget"
    mnu_9:      "Qualité"
    mnu_9_100_0:          "Processus"
    mnu_9_200_0:          "Procédures" 
    mnu_9_300_0:          "Audits" 
    mnu_9_400_0:          "Actions correctives" 
    mnu_9_500_0:          "Revue de direction" 
    mnu_9_600_0:          "Revue de processus" 
    mnu_9_700_0:          "5S" 
    mnu_10:      "Admin. systeme"
    mnu_10_100_0:         "Modification mot de passe "

texte_page:
    #texte page
    txt_1_0:        ""
    #label boutons
        #outillage
    txt_bt_1:       "GED"
    txt_bt_2:       "Courrier Notes"
    txt_bt_3:       "Activite"
    txt_bt_4:       "KPI"
    txt_bt_5:       "Notifications"